// sprites.js
// Contains the image mapping data
// to fetch pieces of the spritesheets.

(function() {

    Crafty.sprite(1, "images/titleSpriteSheet.png", {
        MI_frame:[0, 0, 213, 221],
        MI_title:[0, 232, 500, 155],
        MI_start: [259, 30, 99, 31],
        MI_option:[238, 89, 140, 31],
        MI_credits:[237, 148, 141, 31]
    });

    Crafty.sprite(1, "images/optionsMenuSpriteScreen.png", {
        OI_frame:[0, 0, 620, 780]
    });
    Crafty.sprite(GLOBAL.tileW, "images/spritesheet.png", {
        I_player: [0, 0],
        I_player1BroomLeft: [1,4],
        I_player1BroomRight: [3,9],
        I_player1BroomUp: [1,21],
        I_player1BroomDown: [1,19],
        I_player1PlungerLeft: [1,9],
        I_player1PlungerRight: [3,4],
        I_player1PlungerUp: [4,21],
        I_player1PlungerDown: [4,19],
        I_player1FryingLeft: [5,17],
        I_player1FryingRight: [0,17],
        I_player1FryingUp: [7,21],
        I_player1FryingDown: [7,19],
        I_blobbyLeft: [11,13],
        I_blobbyRight: [5,13],
        I_blobbyUp: [0, 22],
        I_blobbyDown: [0,13],
        I_topDoor: [0, 3],
        I_rightDoor: [1, 3],
        I_bottomDoor: [2, 3],
        I_leftDoor: [3, 3],
        I_floor: [0, 4],
        I_leftWall: [1, 4],
        I_bottomWall: [2, 4],
        I_rightWall: [3, 4],
        I_topWall: [4, 4],
        I_topLeftCorner: [0, 5],
        I_topRightCorner: [1, 5],
        I_bottomLeftCorner: [2, 5],
        I_bottomRightCorner: [3, 5],
        I_kitchenFloor: [0, 6],
        I_kitchenRightWall: [1, 6],
        I_kitchenTopWall: [2, 6],
        I_kitchenLeftWall: [3, 6],
        I_kitchenBottomWall: [4, 6],
        I_redBook:[0,8],
        I_lampLightOn:[1,8],
        I_lampLightOff:[2,8],
        I_blueCouch:[3,8,3],
        I_bloodyCouch:[6,8,3],
        I_statue:[9,8],
        I_blueFlashLight:[10,8],
        I_redFlashLight:[11,8],
        I_yellowFlashLight:[12,8],
        I_noFire:[13,7],
        I_fire:[13,8],
        I_switchOn:[0,9],
        I_switchOff:[1,9],
        I_pressurePlateOff:[2,9],
        I_pressurePlateOn:[3,9],
        I_chestClosed:[4,9],
        I_chestOpen:[5,9],
        I_safe:[6,9],
        I_battery1:[7,9],
        I_battery2:[8,9],
        I_metalKey:[9,9],
        I_woodKey:[10,9],
        I_ironKey:[11,9],
        I_stove:[0,10],
        I_cabinet:[1,10],
        I_waterBottle:[2,10],
        I_sandwich:[3,10],
        I_blueLollipop:[4,10],
        I_greenLollipop:[5,10],
        I_redLollipop:[6,10],
        I_bagOfChips:[7,10],
        I_cannedFood:[8,10],
        I_toiletClosed:[9,10],
        I_toiletOpen:[10,10],
        I_toiletFlush:[11,10],
        I_fridge:[0,11,1,2],
        I_bloodyFridge:[1,11,1,2],
        I_bloodyFridge2:[2,11,1,2],
        I_broom:[3,11,1,2],
        I_equipbroom:[5,13],
        I_wetPlunger:[4,11,1,2],
        I_fryingPan:[5,11,1,2],
        I_brokenLamp:[6,11,1,2],
        I_GemGreen:[10,14],
        I_GemBlue:[11,14],
        I_GemRed:[12,14]
    });

})();